apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: mock-server-git-resource
spec:
  params:
    - name: url
      value: 'https://github.com/makentenza/odata-mock-server.git'
    - name: revision
      value: master
  type: git
